# Generated by Django 5.2.6 on 2025-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('focus', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(max_length=120)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('programs', models.JSONField(blank=True, default=list)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
