# Generated by Django 5.2.6 on 2025-10-01 09:47

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    models_to_process = [
        apps.get_model('hub', 'Person'),
        apps.get_model('hub', 'Community'),
        apps.get_model('hub', 'School'),
    ]

    for model in models_to_process:
        for obj in model.objects.all():
            base_slug = slugify(obj.name)
            if not base_slug:
                base_slug = f"{model.__name__.lower()}-{obj.pk}"

            slug = base_slug
            counter = 1

            while model.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
                counter += 1
                slug = f"{base_slug}-{counter}"

            obj.slug = slug
            obj.save(update_fields=['slug'])


def noop_reverse(apps, schema_editor):
    # No-op reverse migration; leaves existing slugs intact.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RunPython(populate_slugs, noop_reverse),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
    ]
