# Generated by Django 5.2.6 on 2025-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_community_slug_person_slug_school_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed community description'),
        ),
        migrations.AddField(
            model_name='community',
            name='founded_year',
            field=models.IntegerField(blank=True, help_text='Year the community was founded', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Link to community logo/image'),
        ),
        migrations.AddField(
            model_name='community',
            name='member_count',
            field=models.IntegerField(blank=True, help_text='Approximate number of members', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Link to profile photo/avatar'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description'),
        ),
        migrations.AddField(
            model_name='person',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='person',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
    ]
