# Generated by Django 5.2.6 on 2025-10-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_community_description_community_founded_year_and_more'),
    ]

    operations = [
    ]
