# Generated by Django 5.2.6 on 2025-10-12 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20251006_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='community',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact email or information', max_length=150),
        ),
        migrations.AlterField(
            model_name='community',
            name='focus',
            field=models.TextField(blank=True, help_text='Main focus or mission of the community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='founded_year',
            field=models.IntegerField(blank=True, help_text='Year the community was founded', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='community',
            name='links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media and website links'),
        ),
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or region', max_length=120),
        ),
        migrations.AlterField(
            model_name='community',
            name='member_count',
            field=models.IntegerField(blank=True, help_text='Approximate number of members', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='availability',
            field=models.CharField(blank=True, help_text="What they're available for", max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests and skills'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(help_text='Professional role or title', max_length=120),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, help_text='City where the school is located', max_length=120),
        ),
        migrations.AlterField(
            model_name='school',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact information', max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='programs',
            field=models.JSONField(blank=True, default=list, help_text='List of programs offered'),
        ),
    ]
