# Generated by Django 5.2.6 on 2025-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_alter_community_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
